// <auto-generated />
using System;
using CatCentral.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatCentral.Migrations
{
    [DbContext(typeof(CatCentralContext))]
    [Migration("20250222134136_Test3")]
    partial class Test3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatCentral.Models.Food", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(5, 0)");

                    b.Property<string>("SpecialDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Food");
                });

            modelBuilder.Entity("CatCentral.Models.Gallerys", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Age")
                        .HasColumnType("decimal(5, 0)");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ImplantID")
                        .HasColumnType("decimal(9, 0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Gallerys");
                });

            modelBuilder.Entity("CatCentral.Models.Groom", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FoodID")
                        .HasColumnType("int");

                    b.Property<int?>("GallerysID")
                        .HasColumnType("int");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("Supplies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ToyID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FoodID");

                    b.HasIndex("GallerysID");

                    b.HasIndex("ToyID");

                    b.ToTable("Grooming");
                });

            modelBuilder.Entity("CatCentral.Models.Toy", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Toy");
                });

            modelBuilder.Entity("CatCentral.Models.Groom", b =>
                {
                    b.HasOne("CatCentral.Models.Food", "Food")
                        .WithMany("grooms")
                        .HasForeignKey("FoodID");

                    b.HasOne("CatCentral.Models.Gallerys", "Gallerys")
                        .WithMany("grooms")
                        .HasForeignKey("GallerysID");

                    b.HasOne("CatCentral.Models.Toy", "Toy")
                        .WithMany("grooms")
                        .HasForeignKey("ToyID");

                    b.Navigation("Food");

                    b.Navigation("Gallerys");

                    b.Navigation("Toy");
                });

            modelBuilder.Entity("CatCentral.Models.Food", b =>
                {
                    b.Navigation("grooms");
                });

            modelBuilder.Entity("CatCentral.Models.Gallerys", b =>
                {
                    b.Navigation("grooms");
                });

            modelBuilder.Entity("CatCentral.Models.Toy", b =>
                {
                    b.Navigation("grooms");
                });
#pragma warning restore 612, 618
        }
    }
}
